spring:
  # 允许循环依赖
  main:
    allow-circular-references: true
  profiles:
    active: dev
  freemarker:
    checkTemplateLocation: false
  data:
    #mongodb配置
    mongodb.uri: ${mongo_uri:mongodb://127.0.0.1:27017/bcd_gateway}
    #redis配置
    #如果都进行了配置,加载的先后顺序为:
    #sentinel>cluster>single
    redis:
      repositories:
        enabled: false
      #公用配置
      ssl: false
      database: 0
      timeout: 60000
      password: incar@2023
      #异步lettuce连接池(默认)
      lettuce:
        pool:
          maxIdle: 8
          minIdle: 0
          maxActive: 8
          maxWait: -1
        shutdown-timeout: 100ms
      #主从配置
      #     sentinel:
      #       master: myMaster
      #       nodes: 127.0.0.1:23679,127.0.0.1:23680,127.0.0.1:23681
      #    #集群配置
      #     cluster:
      #       maxRedirects: 3
      #       nodes:
      #         - 114.116.107.184:7001
      #         - 114.116.107.184:7002
      #         - 114.116.107.184:7003
      #         - 114.115.141.139:7004
      #         - 114.115.141.139:7005
      #         - 114.115.141.139:7006

      #单机配置
      host: ${server_host:127.0.0.1}
      port: 6379

  #  kafka配置
  kafka:
    consumer:
      bootstrap-servers: ${kafka_bootstrap:10.0.11.42:9092,10.0.11.43:9092,10.0.11.44:9092}
      group-id: ${gateway.id}
      key-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    producer:
      bootstrap-servers: ${kafka_bootstrap:10.0.11.42:9092,10.0.11.43:9092,10.0.11.44:9092}
      key-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

gateway:
  id: ${gateway_id:gw1}
  tcp:
    #tcp端口
    port: 6666
    #tcp会根据此值在redis保存心跳、redis值过期时间为此时间、心跳保存redis周期为(此时间/2-1)
    maxBeforeOffline: 15s
    #kafka topic、多网关之间同一设备session上下线通知
    sessionTopic: bcd-gw-session
